<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		<Reference Include="AAModClassic">
	    	<HintPath>..\ModAssemblies\AAModClassic_v1.0.25.dll</HintPath>
	  	</Reference>
	</ItemGroup>

</Project>